# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://blog.sudoyc.com
date_format: "ordinal"
title: 夏天
subtitle: "个人博客"
description: "夏天的个人博客"
keywords: 夏天, ychost, summer
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/ychost/ychost.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: ychost
organization: UESTC, Univ.
organization_url: http://www.uestc.edu.cn/
location: ChengDu, China
email: ychost@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: ychost
#douban_username: freedim
#facebook_username: mzlogin
weibo_username: ychost-wb
zhihu_username: ychost
#twitter_username: mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: uyan
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: mazhuang
disqus_username: mzlogin
changyan_username: ychost
uyan_username: ychost
# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1

baidu_analytics: true

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, C#, JavaScript]
skill_mobile_app_keywords: [Android]
skill_windows_keywords: [WPF, Office, ASP.NET]


