# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.sudoyc.com
date_format: "ordinal"
title: 夏天
subtitle: "宁静致远"
description: "夏天的个人博客"
keywords: 夏天, ychost, summer
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://cdgithub.com/ychost/ychost.github.io


# ---------------- #
#      Debug       #
# ---------------- #
local_debug: true

# ---------------- #
#     Private      #
# ---------------- #
private_show: true
private_name: "Private"

# ---------------- #
#       Limit      #
# ---------------- #
cat_brif_repo_limit: 3
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: ychost
organization: UESTC, Univ.
organization_url: http://www.uestc.edu.cn/
location: ChengDu, China
email: ychost@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
ihighlight: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: ychost
weibo_username:  ychost-wb
zhihu_username:  ychost


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: uyan, duoshuo,
comments_provider: false
duoshuo_username:  ychost
duoshuo_userid: 6279352103223689985
# ---------------- #
#    Analytics     #
# ---------------- #
baidu_analytics:    false
baidu_analytics_id: 9f767c9440692f340fc3243d48ee3931
cnzz_analytics:     false
cnzz_analytics_id:  1260117641&online=1


# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords:   [Java, C++,  JavaScript, C#]
skill_mobile_app_keywords: [Android, Arduino, C51]
skill_windows_keywords:    [WPF, Office, ASP.NET]


# ---------------- #
#     SEO          #
# ---------------- #
baidu_share:  false
baidu_search: false

# ---------------- #
#     Exclude      #
# ---------------- #
exclude: [Resource]
